Name:               alertmanager-my-release-kube-prometheus-alertmanager
Namespace:          default
CreationTimestamp:  Fri, 26 Feb 2021 22:05:07 +0800
Selector:           alertmanager=my-release-kube-prometheus-alertmanager,app=alertmanager
Labels:             app.kubernetes.io/component=alertmanager
                    app.kubernetes.io/instance=my-release
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=kube-prometheus
                    helm.sh/chart=kube-prometheus-4.1.1
Annotations:        meta.helm.sh/release-name: my-release
                    meta.helm.sh/release-namespace: default
Replicas:           1 desired | 1 total
Update Strategy:    RollingUpdate
Pods Status:        1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           alertmanager=my-release-kube-prometheus-alertmanager
                    app=alertmanager
                    app.kubernetes.io/component=alertmanager
                    app.kubernetes.io/instance=my-release
                    app.kubernetes.io/name=kube-prometheus
  Service Account:  my-release-kube-prometheus-alertmanager
  Containers:
   alertmanager:
    Image:       docker.io/bitnami/alertmanager:0.21.0-debian-10-r232
    Ports:       9093/TCP, 9094/TCP, 9094/UDP
    Host Ports:  0/TCP, 0/TCP, 0/UDP
    Args:
      --config.file=/etc/alertmanager/config/alertmanager.yaml
      --storage.path=/alertmanager
      --data.retention=120h
      --cluster.listen-address=
      --web.listen-address=:9093
      --web.external-url=http://my-release-kube-prometheus-alertmanager.default:9093/
      --web.route-prefix=/
      --cluster.peer=alertmanager-my-release-kube-prometheus-alertmanager-0.alertmanager-operated:9094
      --cluster.reconnect-timeout=5m
    Requests:
      memory:   200Mi
    Liveness:   http-get http://:web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:web/-/ready delay=3s timeout=3s period=5s #success=1 #failure=10
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /alertmanager from alertmanager-my-release-kube-prometheus-alertmanager-db (rw)
      /etc/alertmanager/certs from tls-assets (ro)
      /etc/alertmanager/config from config-volume (rw)
   config-reloader:
    Image:      docker.io/bitnami/prometheus-operator:0.46.0-debian-10-r0
    Port:       8080/TCP
    Host Port:  0/TCP
    Command:
      /bin/prometheus-config-reloader
    Args:
      --listen-address=:8080
      --reload-url=http://127.0.0.1:9093/-/reload
      --watched-dir=/etc/alertmanager/config
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:     100m
      memory:  50Mi
    Environment:
      POD_NAME:   (v1:metadata.name)
      SHARD:     -1
    Mounts:
      /etc/alertmanager/config from config-volume (ro)
  Volumes:
   config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-my-release-kube-prometheus-alertmanager-generated
    Optional:    false
   tls-assets:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-my-release-kube-prometheus-alertmanager-tls-assets
    Optional:    false
   alertmanager-my-release-kube-prometheus-alertmanager-db:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Volume Claims:  <none>
Events:
  Type    Reason            Age   From                    Message
  ----    ------            ----  ----                    -------
  Normal  SuccessfulCreate  10m   statefulset-controller  create Pod alertmanager-my-release-kube-prometheus-alertmanager-0 in StatefulSet alertmanager-my-release-kube-prometheus-alertmanager successful
