apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-26T14:05:07Z"
  labels:
    managed-by: prometheus-operator
    prometheus-name: my-release-kube-prometheus-prometheus
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:managed-by: {}
          f:prometheus-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"97c59179-a0dd-4997-8a60-6e9bb0b04065"}:
            .: {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
    manager: operator
    operation: Update
    time: "2021-02-26T14:05:07Z"
  name: prometheus-my-release-kube-prometheus-prometheus-rulefiles-0
  namespace: default
  ownerReferences:
  - apiVersion: monitoring.coreos.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: Prometheus
    name: my-release-kube-prometheus-prometheus
    uid: 97c59179-a0dd-4997-8a60-6e9bb0b04065
  resourceVersion: "644961"
  selfLink: /api/v1/namespaces/default/configmaps/prometheus-my-release-kube-prometheus-prometheus-rulefiles-0
  uid: add9ecce-9c5b-46ff-a925-d08456637d69
